// <auto-generated />
using System;
using Capstone.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capstone.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Capstone.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOraFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOraInizio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampoId");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("Capstone.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PagamentoEffettuato")
                        .HasColumnType("bit");

                    b.Property<int>("PartitaId")
                        .HasColumnType("int");

                    b.Property<int>("StatoPrenotazione")
                        .HasColumnType("int");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartitaId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Capstone.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartitaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartitaId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Capstone.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Città")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GestoreId")
                        .HasColumnType("int");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrezzoOrario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoCampo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValutazioneMedia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GestoreId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("Capstone.Models.FieldManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FieldManagers");
                });

            modelBuilder.Entity("Capstone.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampoId")
                        .HasColumnType("int");

                    b.Property<int>("CreatoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int>("TipoPartita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampoId");

                    b.HasIndex("CreatoreId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Capstone.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MittenteId")
                        .HasColumnType("int");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("MittenteId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Capstone.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRecensione")
                        .HasColumnType("datetime2");

                    b.Property<int>("Punteggio")
                        .HasColumnType("int");

                    b.Property<int>("TipoRecensione")
                        .HasColumnType("int");

                    b.Property<int?>("ValutatoCampoId")
                        .HasColumnType("int");

                    b.Property<int?>("ValutatoGiocatoreId")
                        .HasColumnType("int");

                    b.Property<int>("ValutatoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ValutatoCampoId");

                    b.HasIndex("ValutatoGiocatoreId");

                    b.HasIndex("ValutatoreId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Capstone.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeRuolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Capstone.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PartiteGiocate")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RuoloPreferito")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValutazioneMedia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Capstone.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("UserMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MatchId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMatch");
                });

            modelBuilder.Entity("Capstone.Models.Availability", b =>
                {
                    b.HasOne("Capstone.Models.Field", "Campo")
                        .WithMany("Disponibilità")
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campo");
                });

            modelBuilder.Entity("Capstone.Models.Booking", b =>
                {
                    b.HasOne("Capstone.Models.Match", "Partita")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("PartitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone.Models.User", "Utente")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partita");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Capstone.Models.Chat", b =>
                {
                    b.HasOne("Capstone.Models.Match", "Partita")
                        .WithOne("Chat")
                        .HasForeignKey("Capstone.Models.Chat", "PartitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partita");
                });

            modelBuilder.Entity("Capstone.Models.Field", b =>
                {
                    b.HasOne("Capstone.Models.FieldManager", "Gestore")
                        .WithMany("CampiGestiti")
                        .HasForeignKey("GestoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gestore");
                });

            modelBuilder.Entity("Capstone.Models.Match", b =>
                {
                    b.HasOne("Capstone.Models.Field", "Campo")
                        .WithMany("Partite")
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone.Models.User", "Creatore")
                        .WithMany("PartiteCreate")
                        .HasForeignKey("CreatoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campo");

                    b.Navigation("Creatore");
                });

            modelBuilder.Entity("Capstone.Models.Message", b =>
                {
                    b.HasOne("Capstone.Models.Chat", "Chat")
                        .WithMany("Messaggi")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone.Models.User", "Mittente")
                        .WithMany("MessaggiInviati")
                        .HasForeignKey("MittenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Mittente");
                });

            modelBuilder.Entity("Capstone.Models.Review", b =>
                {
                    b.HasOne("Capstone.Models.Field", "ValutatoCampo")
                        .WithMany()
                        .HasForeignKey("ValutatoCampoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capstone.Models.User", "ValutatoGiocatore")
                        .WithMany("RecensioniRicevute")
                        .HasForeignKey("ValutatoGiocatoreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capstone.Models.User", "Valutatore")
                        .WithMany("RecensioniLasciate")
                        .HasForeignKey("ValutatoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ValutatoCampo");

                    b.Navigation("ValutatoGiocatore");

                    b.Navigation("Valutatore");
                });

            modelBuilder.Entity("Capstone.Models.UserRole", b =>
                {
                    b.HasOne("Capstone.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserMatch", b =>
                {
                    b.HasOne("Capstone.Models.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Capstone.Models.Chat", b =>
                {
                    b.Navigation("Messaggi");
                });

            modelBuilder.Entity("Capstone.Models.Field", b =>
                {
                    b.Navigation("Disponibilità");

                    b.Navigation("Partite");
                });

            modelBuilder.Entity("Capstone.Models.FieldManager", b =>
                {
                    b.Navigation("CampiGestiti");
                });

            modelBuilder.Entity("Capstone.Models.Match", b =>
                {
                    b.Navigation("Chat")
                        .IsRequired();

                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("Capstone.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Capstone.Models.User", b =>
                {
                    b.Navigation("MessaggiInviati");

                    b.Navigation("PartiteCreate");

                    b.Navigation("Prenotazioni");

                    b.Navigation("RecensioniLasciate");

                    b.Navigation("RecensioniRicevute");
                });
#pragma warning restore 612, 618
        }
    }
}
